#!/usr/bin/env ruby
# frozen_string_literal: true

require 'forest'
require 'course'

forest = Forest.new('input.txt')

course = Course.new(forest: forest, slope: Slope.new(right: 3, down: 1))

puts format('encountered %d trees', course.trees)

courses = [
  [1, 1],
  [3, 1],
  [5, 1],
  [7, 1],
  [1, 2]
].map { |right, down| Course.new(forest: forest, slope: Slope.new(right: right, down: down)) }

puts format('product of courses is %d', courses.map(&:trees).reduce(:*))
